apiVersion: v1
kind: Service
metadata:
  name: app-bachelor-service
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: app-bachelor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-bachelor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-bachelor
  template:
    metadata:
      labels:
        app: app-bachelor
    spec:
      volumes:
      - name: html
        emptyDir: {}
      containers:
      - name: nginx
        image: nginx:1.17.3
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
        ports:
        - containerPort: 80
      - name: bachelor-chow
        image: zarl/bachelor_chow:version0.1
        volumeMounts:
        - name: html
          mountPath: /root/html
